# Generated by Django 5.1.7 on 2025-04-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_state_sight_description_sight_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
