# Generated by Django 5.2 on 2025-04-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_category_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.state'),
        ),
        migrations.CreateModel(
            name='SightCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categorie')),
                ('sight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sight')),
            ],
        ),
    ]
